### ISSUE TITLE
Repo goals?

### ISSUE THREAD

**Issue by placer14** [cpacia/openbazaar3.0#1]
I noticed you're still putting time into this and I have some questions:
- What the goals of this effort?
- How are you planning on introducing these changes, if at all?
- If you are, what are you doing to ensure network compatibility w 2.0, if at all?

**Comment by cpacia** [comment]
I don't know what the goals are. It's up to everyone else if they want to use it or not. Obviously I think our time would be better spent pursuing this route. Pretty sure it would be done by now (with Ethereum) if we focused our time on this instead of the current repo. You can move much faster when not bogged down by tech debt. 

But it's just a side project for now. 

As far at compatibility. We can migrate existing data from the old format into this one, but I don't think we can do anything about open orders. People would need to finish open orders before migrating.
